services:
  - type: web
    name: whatsapp-chatbot
    env: python
    rootDir: backend  # 👈 essentiel pour que Render exécute depuis ce dossier
    buildCommand: pip install -r ../requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: WHATSAPP_TOKEN
        sync: false
      - key: WHATSAPP_PHONE_ID
        sync: false
      - key: VERIFY_TOKEN
        sync: false
      - key: OPENAI_API_KEY
        sync: false
